# COURSE: A deep understanding of deep learning
## SECTION: Math prerequisites
### LECTURE: Matrix multiplication
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202303

In [1]:
# import libraries
import numpy as np
import torch

# Using numpy

In [2]:
# create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications...
print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@C   ,2)), print(' ')
# print(np.round( B@C   ,2)), print(' ')
print(np.round( C.T@A ,2))

[[ 0.36 -0.87 -1.09 -0.56  2.58]
 [-1.29 -0.89  0.37 -1.54 -0.14]
 [-1.06  0.56  1.59 -0.44 -2.44]]
 
[[ 5.74 -0.53 -0.57  1.29]
 [-6.07 -0.4   1.42 -1.6 ]
 [ 0.03 -1.15  1.1  -0.42]
 [ 1.26  2.66 -2.34  0.84]
 [-2.34  2.41 -1.37 -0.23]
 [ 0.56  2.5  -2.12  0.67]
 [ 0.74 -2.3   1.49 -0.06]]


# Using pytorch

In [3]:
# create some random matrices
A  = torch.randn(3,4)
B  = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1,dtype=torch.float )

# try some multiplications...
# print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@B.T ,2)), print(' ')
print(np.round( A@C1  ,2)), print(' ')
print(np.round( A@C2  ,2))

tensor([[-2.2200,  0.4900, -0.3900,  0.0200, -2.6400, -1.2400, -1.6200],
        [ 1.4200,  0.5500, -0.2200,  0.0700,  2.1300,  1.2800,  0.4200],
        [-2.9800,  1.8100, -4.8000, -0.4100, -0.4900, -1.9200,  0.1600]],
       dtype=torch.float64)
 
tensor([[-2.2200,  0.4900, -0.3900,  0.0200, -2.6400, -1.2400, -1.6200],
        [ 1.4200,  0.5500, -0.2200,  0.0700,  2.1300,  1.2800,  0.4200],
        [-2.9800,  1.8100, -4.8000, -0.4100, -0.4900, -1.9200,  0.1600]])
